palantirnet/federated-search-react

src/components/results/result.js

https://palantir.atlassian.net/browse/UMHS-21
Description:
- Display links to content on all sites 
- (the content will need to be indexed on the https://github.com/palantirnet/search_api_federated_solr/pull/41 branch)
- (Content that haven't been indexed on the above branch won't display any site_names)

Updated results component to list sitename links

---

package.json
src/components/results/result.js

Updated results to display old ss_sitename field when needed so that Nodes that haven't been re-indexed still work.

Updated results to display old sitename field when needed

---

package.json
src/components/results/result.js
src/components/sort-menu/_search-scope.scss
src/imgs/chevron-small-down.svg
src/styles.css
yarn.lock

- Fixes decoded apostrophe in carrots entry <img width="699" alt="screenshot_9_28_18__12_22_pm" src="https://user-images.githubusercontent.com/238201/46223474-22307580-c319-11e8-982c-4a0980f91e09.png">
- Fixes missing `chevron-small-down` in https://github.com/palantirnet/search_api_federated_solr/pull/44/files
- Fixes site not loading in Safari on iOS9 due to missing `intl` library
- Fixes warning from https://github.com/palantirnet/federated-search-react/pull/16/files#diff-44b6781b2e9835557c3df782d1250b97R42

Results bugfix

---

src/components/current-query/index.js
src/components/federated-solr-faceted-search.js
src/components/list-facet/index.js
src/components/results/result.js
src/index.js

[See Comment on UMHS-21](https://palantir.atlassian.net/browse/UMHS-21?focusedCommentId=54225&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-54225)
In altering the site_name field to be indexed as multi-valued, the site name filter no longer worked.
Fixed site name filter to work with multi-field site-name field.
- Find and replace all instances of `ss_site_name` with `sm_site_name` and filters began working again!
- Verify the functionality is truely working properly with the "Find and replace" solution above.
- My concern is that the `sm_site_name` is now and array instead of a string, so I'd imagine there should be some logic that need be updated.

HOTFIX-UMUS-21-fix-sitename-filter

---

src/components/results/count-label.js
src/index.js

While testing I discovered that a search resulting in exactly one page of results will barf due to a missing condition. Resolved this, and hid some long-standing debugging code.

Paging bug

---

src/.env.local.js.example
src/components/federated-solr-faceted-search.js
src/components/results/result.js
src/index.js

To test:
- Create or edit `.env.local.js` and set the following 
```
url: "https://ss826806-us-east-1-aws.measuredsearch.com:443/solr/master/select",
userpass: btoa("palantir:palantirqauser"),
```
- `yarn start`
- Search for "breastfeeding"
- Observe "Breastfeeding Resources" links to the same url as the first item in the list of sites (CS Mott...)
- Edit `.env.local.js` and set: `hostname: "umwomenshealth.org",`
- Observe the site reloads and "Breastfeeding Resources now links to Von Voigtlander Women's Hospital.

UMUS-21 Update link behavior to use urls field

---

src/components/list-facet/index.js
src/components/results/result.js

Resolves two issues:
- application crashes if no `urls` field exists (see report from [UMHS-24](https://palantir.atlassian.net/browse/UMHS-24))
- empty strings in `sm_federated_terms` field can cause funky empty dropdown.

UMHS-24 render error

---

src/.env.local.js.example
src/components/current-query/index.js
src/components/federated-solr-faceted-search.js
src/components/text-search/search-as-you-type.js
src/index.js

This PR adds functionality that will enable `search_api_federated_solr` implementers to select filter/facet fields that they'd like to be hidden in the UI.  
Note that this functionality does not preclude those fields from being pre-set and sent in the query (however, at this point only the site name can be set and sent in this way as of now).
1. Check out master in the [Drupal federated-search-demo](https://github.com/palantirnet/federated-search-demo) project
1. Boot the vm `vagrant up`, ssh in to the vm `vagrant ssh` and [build the sites](https://github.com/palantirnet/federated-search-demo#rebuild-all-the-things) with `phing build install-all init`
1. Log in to the standalone d8 site `drush @fsd-d8.local uli`
1. Clear + reindex all items in the index at: …

Root 198 enable ui hide facets filters

---

src/components/current-query/index.js
src/components/federated-solr-faceted-search.js
src/components/list-facet/index.js
src/components/search-field-container.js
src/helpers/index.js
src/index.js

This PR adds functionality to the search app which tracks the state of federated term facets in the qs:
- on app load the state of the federated terms search field will be set based on any terms passed in via the url qs with the following syntax: `federated_terms[]=group>value`
- note the `[]` which tell the qs parser to expect/allow multiple values to be set 
- the current query component will remove the appropriate item from the url qs when its corresponding active filter button clicked
- the sidebar filter list facet component will either add or remove the appropriate item from the url qs when its corresponding input is toggled
- on app load the expand / collapse state of the search filters and facets will be determined by the presence / absence (respectively) of the corresponding …

Root 198 track term facets in qs

---

src/.env.local.js.example
src/components/text-search/search-as-you-type.js
yarn.lock

This PR implements latest updates to https://github.com/palantirnet/solr-faceted-search-react/pull/7 which makes the search app un-opinionated about main + autocomplete query default / query fields.  This allows flexibility with the default search, autocomplete, and enables field boosting to be set in solr config.
Queries now have the following structure:
- main query: `q=<mainQueryField.value>` as opposed to `q=tm_rendered_item:<mainQueryField.value>`
- autocomplete query when `autocomplete.appendWildcard` is true: `q=<mainQueryField.value>+<mainQueryField.value>*&df=mainQueryField.field` 
- autocomplete query when `autocomplete.appendWildcard` is false (default): `q=<mainQueryField.value>`
See [the updates to the solr client repo …

ROOT-198: remove default field from queries, make autocomplete wildcard* configurable

---

src/components/results/_pagination.scss
src/components/results/_search-results-stat.scss
src/components/results/_search-results.scss
src/styles.css

We shouldn't over-style in this base module.

Rewire CSS to use new classes and clean up.

---

.eslintrc
README.md
package.json
src/.env.local.js.example
src/components/_aside.scss
src/components/_search-filters.scss
src/components/current-query/_applied-filters.scss
src/components/current-query/index.js
src/components/federated-solr-faceted-search.js
src/components/list-facet/index.js
src/components/range-facet/index.js
src/components/results/_pagination.scss
src/components/results/_search-results-stat.scss
src/components/results/_search-results.scss
src/components/results/count-label.js
src/components/sort-menu/_search-scope.scss
src/components/text-search/_autocomplete.scss
src/components/text-search/_search-form.scss
src/components/text-search/index.js
src/components/text-search/no-autocomplete.js
src/components/text-search/search-as-you-type.js
src/helpers/index.js
src/index.js
src/styles.css
src/styles.scss
yarn.lock

This PR adds the option of enabling a configuring the main query text field to implement search as you type functionality, taking advantage of new functionality built in https://github.com/palantirnet/solr-faceted-search-react/pull/7
1. Check out master in the [Drupal federated-search-demo](https://github.com/palantirnet/federated-search-demo) project
1. Boot the vm `vagrant up`, ssh in to the vm `vagrant ssh` and [build the sites](https://github.com/palantirnet/federated-search-demo#rebuild-all-the-things) with `phing build-all init`
1. Log in to the standalone d8 site `drush @fsd-d8.local uli`
1. Clear + reindex all items in the index at: http://d8.fs-demo.local/admin/config/search/search-api/index/federated_search_index
1. Note: we'll be using the index provided by the demo site, but …

Root 198: add search-as-you-type autocomplete functionality option to text search

---

package.json
src/.env.local.js.example
src/index.js
yarn.lock

Adds ability to use solr proxy for search.  See https://github.com/palantirnet/search_api_federated_solr/pull/79

Root 863 enable solr proxy

---

src/components/results/result.js

This PR updates the logic in rendering a search result URL: it now defaults to using the canonical URL.

umhs-28: default to canonical url in results

---

package.json
src/.env.local.js.example
src/index.js
yarn.lock

Adds a flag indicating D7 site so solr client knows to make request to proxy using `search` instead of `q` param
Includes test for updated version of the react solr client: https://github.com/palantirnet/solr-faceted-search-react/pull/9

Platform-1002: send search param for d7

---

src/components/results/result.js

Adds logic for determining search result url, respecting canonical url, to 2.x

UMHS-28: use canonical url

---

src/components/list-facet/index.js
src/index.js

If you configure the site to mimic the report in https://www.drupal.org/project/search_api_federated_solr/issues/3082487#comment-13269125, then two `sm_site_name` values will be set in the `fq` element of the query.
This change removes that error.
To test, toggle these items in the `env.local.js` file into their 4 distinct options (both on, one on, both off).
```
siteSearch:
hiddenSearchFields: (sm_site_name hidden)
```

Improves logic in the default site name value to prevent duplicate values in the 'fq' param

---

patches/react-autosuggest+9.4.3.patch
patches/react-dates+21.8.0.patch
src/components/range-facet/index.js
src/components/text-search/no-autocomplete.js
src/components/text-search/search-as-you-type.js

[FS-23: Browser console errors from package updates](https://palantir.atlassian.net/browse/FS-23)
- Addressing browser console errors for `componentWillReceiveProps`
- I replaced two warnings coming from the federated search by using `componentDidUpdate` for following components:  
- `FederatedRangeFacet` (when the date range facet is cleared)
- `FederatedTextSearchNoAutocomplete` (applies when autocomplete is enabled in `.env.local.js`)
And used prefixed `UNSAFE_` for:
- For `FederatedTextSearchAsYouType` component in federated search, I prefixed the lifecycle with a `UNSAFE_`, as updating the lifecycle to `componentDidUpdate` caused a fatal nesting error on render. We might need to open a new ticket to address this independently, there could additional work around this upgrade. There is …

FS-23: Browser console errors from package updates

---

package.json
patches/react-scripts+3.3.1.patch
src/components/list-facet/index.js
src/components/range-facet/index.js
src/components/results/pagination.js
yarn.lock

[FS-27: Update mem and webpack-dev-server](https://palantir.atlassian.net/browse/FS-27)
- Resolves security alerts warnings for `webpack-dev-server` and `mem`
- Switched packages to `react-scripts` from `@palantirnet/react-scripts`. The `@palantirnet/react-scripts` was causing a majority of the security alerts. It doesn't seem like it being used other than supplying an important custom variable value. The `@palantirnet/react-scripts`package  was mostly adding its own `include` value in the `webpack.config.js` file. It was forked from `react-scripts` package and was on version `1.1.14` - hence the large volume of security warnings. This might need to be further explored and not in a patch.
- Replaces `include` value with `[paths.appSrc, …

FS-27: Security alert for webpack-dev-server and mem

---

src/components/current-query/_fs-applied-filters.scss
src/components/current-query/index.js
src/components/text-search/_fs-autocomplete.scss
src/components/text-search/search-as-you-type.js
src/styles.css

So when I merged in all of our work, the application broke. 
Part of it is namespacing on the autocomplete CSS, which I have marked here.
But now I get an error after clearing the search term.
```
TypeError: state is not iterable
setSuggestQueryField
node_modules/solr-faceted-search-react/src/reducers/suggestQuery.js:12
9 | const setSuggestQueryField = (state, action) => {
10 |   // Clear the suggestQueryField data only if the search field has been cleared.
11 |   if (action.newFields.filter(field => field.field === "tm_rendered_item" && field.value ==="").length) {
> 12 |     return Object.assign({},
13 |       ...state,
14 |       {
15 |         suggestQuery: {
```
There is also a build notice about HTML accessibility, viewable on `yarn start`:
```
Line 27:9:   The href attribute is …
```

Application CSS conflicts with new namespace

---

README.md
cypress.json
cypress/fixtures/example.json
cypress/integration/app.test.js
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/index.js
package.json
yarn.lock

[FS-49: Adding cypress testing](https://palantir.atlassian.net/browse/FS-49)
- Adds `cypress` package to `devDependencies`
- Adds setup configuration for `cypress`
- Updates `scripts` in `package.json` to run cypress
- Adds `cypress.json` configuration file
- Updates `README.md`
- Adds some basic test coverage of application 
- Tests if key markups are rendered on the DOM
- Verify demo box is running for Solr index to be queried. If not, the test will time out and result in a timeout/error message.
- Should there be more automation in this approach? Would running `yarn cypress` to run tests be missed for future developers?  
- Cypress requires a `cypress.json` file to be added with a defined `baseUrl` with the value `localhost:3000`. I can see if there are other ports it might cause some …

FS-49: Adding cypress testing framework

---

src/components/search-field-container.js

To test
Run `yarn start` and view `localhost`
Verify that when resizing to mobile view, the facets are `hidden` until `+` is clicked.
Verify that when resizing to desktop, the facets after 900 are `shown`

Add onResize for show/hide on facets.

---

src/.env.local.js.example

Was getting "FALSE is not defined" in the console when using this example config. This updates the values to the lower-case `false`.

fix "FALSE is not defined" errors
